import { Matches } from './match';

export const MATCHES: Matches[] = [
  { mno: 1, btw: 'PMG Enterprise v/s Yash 11', toss: 'Yash 11 decided to Bowl First', venue: 'Ekjut Cricket Stadium', date: '24-01-2021', result: 'Yash 11', mom: 'Nikhil', scores: { os: '60/2', sc: '63/1', highrunone: { name: 'Bhagvan', runs: 23 }, highruntwo: { name: 'Nikhil*', runs: 33 }, highwicone: { name: 'Prathmesh Kadam', wick: 1 }, highwictwo: { name: 'Rakesh', wick: 1 } } },
  { mno: 2, btw: 'MangalMurti 11 v/s Mauli Bhumika Super', toss: 'Mauli Bhumika Super decided to Bowl First', venue: 'Ekjut Cricket Stadium', date: '24-01-2021', result: 'MangalMurti 11', mom: 'Sumit', scores: { os: '53/3', sc: '34/5', highrunone: { name: 'Sumit', runs: 36 }, highruntwo: { name: 'Hiroji', runs: 16 }, highwicone: { name: 'Prathmesh Gaonkar', wick: 1 }, highwictwo: { name: 'Digamber', wick: 3 } } },
  { mno: 3, btw: 'Mauli Bhumika Super v/s Yash 11', toss: 'Yash 11 decided to Bowl First', venue: 'Ekjut Cricket Stadium', date: '24-01-2021', result: 'Mauli Bhumika Super', mom: 'Prathmesh Gaonkar', scores: { os: '69/4', sc: '60/1', highrunone: { name: 'Prathmesh Gaonkar', runs: 30 }, highruntwo: { name: 'Govind*', runs: 32 }, highwicone: { name: 'Pundalik', wick: 2 }, highwictwo: { name: 'Prasad', wick: 1 } } },
  { mno: 4, btw: 'MangalMurti 11 v/s PMG Enterprise', toss: 'PMG Enterprise Super decided to Bowl First', venue: 'Ekjut Cricket Stadium', date: '24-01-2021', result: 'MangalMurti 11', mom: 'Sumit Kadam', scores: { os: '63/5', sc: '51/7', highrunone: { name: 'Vidhish', runs: 15 }, highruntwo: { name: 'Sairaj', runs: 9 }, highwicone: { name: 'Sairaj', wick: 2 }, highwictwo: { name: 'Sarvesh', wick: 2 } } },
  { mno: 5, btw: 'MangalMurti 11 v/s Yash 11', toss: 'MangalMurti 11 Super decided to Bowl First', venue: 'Ekjut Cricket Stadium', date: '24-01-2021', result: 'Yash 11 win in Super  Over', mom: 'Prathmesh Kadam', scores: { os: '52/4', sc: '52/3', highrunone: { name: 'Santosh', runs: 20 }, highruntwo: { name: 'Kishna Sawant', runs: 39 }, highwicone: { name: 'Sumit Kadam', wick: 2 }, highwictwo: { name: 'Nikhil', wick: 2 } } },
  { mno: 6, btw: 'PMG Enterprise v/s Mauli Bhumika Super', toss: 'Mauli Bhumika Super decided to Bowl First', venue: 'Ekjut Cricket Stadium', date: '24-01-2021', result: 'Mauli Bhumika Super', mom: 'Prasad', scores: { os: '54/6', sc: '59/0', highrunone: { name: 'SaiRaj', runs: 18 }, highruntwo: { name: 'Prathmesh Gaonkar', runs: 25 }, highwicone: { name: 'Sameer Mestri', wick: 2 }, highwictwo: null } },
];
